name: core-tests

on: push

jobs:
  run-core-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/everest/everest-demo/manager:2025.6.1-dt-esdp
    steps:
      - name: Run core tests
        run: sh /ext/source/tests/run-test.sh
